/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ContractAPIService is a service that implements the logic for the ContractAPIServicer
// This service should implement the business logic for every endpoint for the ContractAPI API.
// Include any external packages or services that will be required by this service.
type ContractAPIService struct {
}

// NewContractAPIService creates a default api service
func NewContractAPIService() ContractAPIServicer {
	return &ContractAPIService{}
}

// CalculateRate - Calculate rate
func (s *ContractAPIService) CalculateRate(ctx context.Context, rateCalculationReq RateCalculationReq) (ImplResponse, error) {
	// TODO - update CalculateRate with the required logic for this service method.
	// Add api_contract_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, RateRes{}) or use other options such as http.Ok ...
	// return Response(200, RateRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CalculateRate method not implemented")
}

// CreateContract - Create a new contract
func (s *ContractAPIService) CreateContract(ctx context.Context, contractReq ContractReq) (ImplResponse, error) {
	// TODO - update CreateContract with the required logic for this service method.
	// Add api_contract_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, ContractRes{}) or use other options such as http.Ok ...
	// return Response(201, ContractRes{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateContract method not implemented")
}

// GetContract - 
func (s *ContractAPIService) GetContract(ctx context.Context, contractId string) (ImplResponse, error) {
	// TODO - update GetContract with the required logic for this service method.
	// Add api_contract_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ContractRes{}) or use other options such as http.Ok ...
	// return Response(200, ContractRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetContract method not implemented")
}

// GetCustomerContracts - Get customer contracts
func (s *ContractAPIService) GetCustomerContracts(ctx context.Context, customerId string, page int32, pageSize int32) (ImplResponse, error) {
	// TODO - update GetCustomerContracts with the required logic for this service method.
	// Add api_contract_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ContractRes{}) or use other options such as http.Ok ...
	// return Response(200, []ContractRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCustomerContracts method not implemented")
}
